---
version: "2"

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: false

linters:
  default: all
  disable:
    - gomodguard
    - wsl
  settings:
    lll:
      line-length: 140
      tab-width: 4
    unparam:
      check-exported: true
  exclusions:
    presets: []
    rules:
      - text: 'G104'
        linters:
          - gosec

formatters:
  enable:
    - gofmt
    - goimports
