---
# Shared configuration for all tests.

instances:
  - region: us-east-2
    instance: pmm-qa-aurora3-mysql-instance-1
  - region: us-east-2
    instance: pmm-qa-aurora-postgres-13-5-instance-1
  - region: us-east-2
    instance: pmm-qa-rds-mysql-8-4
  - region: us-east-2
    instance: pmm-qa-pgsql-16
  - region: us-east-2
    instance: no-such-instance
