FROM golang:1.19.0-alpine as build
WORKDIR /app
COPY . .
RUN env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /rds_exporter ./
RUN chmod +x /rds_exporter

FROM alpine:latest
COPY --from=build ["/rds_exporter", "/bin/" ]
RUN apk update && \
    apk add ca-certificates && \
    update-ca-certificates
EXPOSE 9042
ENTRYPOINT [ "/bin/rds_exporter", "--config.file=/etc/rds_exporter/config.yml" ]
