{
 "title": "AWS RDS Enhanced",
 "tags": [
  "AWS",
  "RDS",
  "Enhanced"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Region",
    "label": "Region",
    "query": {
     "query": "label_values(rdsosmetrics_timestamp{job=~\"prom-rds-exporter\"}, region)"
    }
   },
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values(rdsosmetrics_timestamp{job=~\"prom-rds-exporter\"}, exported_instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "OVERVIEW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number vCPUs",
   "type": "stat",
   "description": "RDS OS Metrics - The number of virtual CPUs for the DB instance",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rdsosmetrics_General_numVCPUs{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization - Total",
   "type": "gauge",
   "description": "RDS OS Metrics - The total percentage of the CPU in use. This value includes the nice value",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rdsosmetrics_cpuUtilization_total{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Load Average 1 Minute ",
   "type": "timeseries",
   "description": "RDS OS Metrics - The number of processes requesting CPU time over the last minute",
   "gridPos": { "h": 8, "w": 5, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rdsosmetrics_loadAverageMinute_one{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Load Average 5 Minutes ",
   "type": "timeseries",
   "description": "RDS OS Metrics - The number of processes requesting CPU time over the last 5 minutes",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rdsosmetrics_loadAverageMinute_five{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Load Average 15 Minutes ",
   "type": "timeseries",
   "description": "RDS OS Metrics - The number of processes requesting CPU time over the last 15 minutes",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rdsosmetrics_loadAverageMinute_fifteen{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Total percentage of used memory",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(node_memory_Active_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"})/(node_memory_MemTotal_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"})*100"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "description": "Total percentage of used disk",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100-((node_filesystem_avail_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"})/(node_filesystem_size_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"})*100)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "bargauge",
     "description": "The percentage of CPU utilization",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "node_cpu_average{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "CPU Utilization - Total",
     "type": "gauge",
     "description": "RDS OS Metrics - The total percentage of the CPU in use. This value includes the nice value",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rdsosmetrics_cpuUtilization_total{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "CPU Utilization - System",
     "type": "gauge",
     "description": "RDS OS Metrics - The percentage of CPU in use by the kernel",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rdsosmetrics_cpuUtilization_system{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "CPU Utilization - User",
     "type": "gauge",
     "description": "RDS OS Metrics - The percentage of CPU in use by user programs",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rdsosmetrics_cpuUtilization_user{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "CPU Utilization - Guest",
     "type": "gauge",
     "description": "RDS OS Metrics - The percentage of CPU in use by guest programs",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rdsosmetrics_cpuUtilization_guest{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "CPU Utilization - Nice",
     "type": "gauge",
     "description": "RDS OS Metrics - The percentage of CPU in use by programs running at lowest priority",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rdsosmetrics_cpuUtilization_nice{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "CPU Utilization - Steal",
     "type": "gauge",
     "description": "RDS OS Metrics - The percentage of CPU in use by other virtual machines",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rdsosmetrics_cpuUtilization_steal{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "CPU Utilization - Irq",
     "type": "gauge",
     "description": "RDS OS Metrics - The percentage of CPU in use by software interrupts",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rdsosmetrics_cpuUtilization_irq{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "CPU Utilization - Wait",
     "type": "gauge",
     "description": "RDS OS Metrics - The percentage of CPU unused while waiting for I/O access",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rdsosmetrics_cpuUtilization_wait{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "CPU Utilization - Idle",
     "type": "gauge",
     "description": "RDS OS Metrics - The percentage of CPU that is idle",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rdsosmetrics_cpuUtilization_idle{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    }
   ]
  },
  {
   "title": "MEMORY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Memory",
     "type": "stat",
     "description": "RDS OS Metrics - The total amount of memory, in kilobytes",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rdsosmetrics_memory_total{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Memory Active",
     "type": "timeseries",
     "description": "RDS OS Metrics - The amount of assigned memory, in kilobytes",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_memory_active{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Memory Inactive",
     "type": "timeseries",
     "description": "RDS OS Metrics - The amount of least-frequently used memory pages, in kilobytes",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_memory_inactive{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Memory Free",
     "type": "timeseries",
     "description": "RDS OS Metrics - The amount of unassigned memory, in kilobytes",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_memory_free{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Memory Cached",
     "type": "timeseries",
     "description": "RDS OS Metrics - The amount of memory used for caching file system–based I/O",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_memory_cached{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Memory Buffers",
     "type": "timeseries",
     "description": "RDS OS Metrics - The amount of memory used for buffering I/O requests prior to writing to the storage device, in kilobytes",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_memory_buffers{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory MemTotal Bytes",
     "type": "timeseries",
     "description": "Memory information field MemTotal_bytes",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory Active Bytes",
     "type": "timeseries",
     "description": "Memory information field Active_bytes",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Active_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory Inactive Bytes",
     "type": "timeseries",
     "description": "Memory information field Inactive_bytes",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Inactive_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory MemFree Bytes",
     "type": "timeseries",
     "description": "Memory information field MemFree_bytes",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemFree_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory Cached Bytes",
     "type": "timeseries",
     "description": "Memory information field Cached_bytes",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Cached_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory Buffers Bytes",
     "type": "timeseries",
     "description": "Memory information field Buffers_bytes",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Buffers_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Memory Writeback",
     "type": "timeseries",
     "description": "RDS OS Metrics - The amount of dirty pages in RAM that are still being written to the backing storage, in kilobytes",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_memory_writeback{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Memory Dirty",
     "type": "timeseries",
     "description": "RDS OS Metrics - The amount of memory pages in RAM that have been modified but not written to their related data block in storage, in kilobytes",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_memory_dirty{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Memory Huge Pages Total",
     "type": "timeseries",
     "description": "RDS OS Metrics - The total number of huge pages for the system",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_memory_hugePagesTotal{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Memory Mapped",
     "type": "timeseries",
     "description": "RDS OS Metrics - The total amount of file-system contents that is memory mapped inside a process address space, in kilobytes",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_memory_mapped{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Memory Page Tables ",
     "type": "timeseries",
     "description": "RDS OS Metrics - The amount of memory used by page tables, in kilobytes",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_memory_pageTables{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Memory Slab",
     "type": "timeseries",
     "description": "RDS OS Metrics - The amount of reusable kernel data structures, in kilobytes",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_memory_slab{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory Writeback Bytes",
     "type": "timeseries",
     "description": "Memory information field Writeback_bytes",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Writeback_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory Dirty Bytes",
     "type": "timeseries",
     "description": "Memory information field Dirty_bytes",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Dirty_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory HugePages Total",
     "type": "timeseries",
     "description": "Memory information field HugePages_Total",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_HugePages_Total{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory Mapped Bytes",
     "type": "timeseries",
     "description": "Memory information field Mapped_bytes",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Mapped_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory PageTables Bytes",
     "type": "timeseries",
     "description": "Memory information field PageTables_bytes",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_PageTables_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory Slab Bytes",
     "type": "timeseries",
     "description": "Memory information field Slab_bytes",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Slab_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Memory Huge Pages Free",
     "type": "timeseries",
     "description": "RDS OS Metrics - The number of free huge pages. Huge pages are a feature of the Linux kernel",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_memory_hugePagesFree{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Memory Huge Pages Surp ",
     "type": "timeseries",
     "description": "RDS OS Metrics - The number of available surplus huge pages over the total",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_memory_hugePagesSurp{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Memory Huge Pages Rsvd ",
     "type": "timeseries",
     "description": "RDS OS Metrics - The number of committed huge pages",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_memory_hugePagesRsvd{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory SwapTotal Bytes",
     "type": "timeseries",
     "description": "Memory information field SwapTotal",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory SwapCached Bytes",
     "type": "timeseries",
     "description": "Memory information field SwapCached",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_SwapCached_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory SwapFree Bytes",
     "type": "timeseries",
     "description": "Memory information field SwapFree",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_SwapFree_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory HugePages Free",
     "type": "timeseries",
     "description": "Memory information field HugePages_Free",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_HugePages_Free{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory HugePages Surp",
     "type": "timeseries",
     "description": "Memory information field HugePages_Surp",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_HugePages_Surp{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory HugePages Rsvd",
     "type": "timeseries",
     "description": "Memory information field HugePages_Rsvd",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_HugePages_Rsvd{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Memory Huge Pages Size ",
     "type": "timeseries",
     "description": "RDS OS Metrics - The size for each huge pages unit, in kilobytes",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_memory_hugePagesSize{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node Memory Hugepagesize Bytes",
     "type": "timeseries",
     "description": "Memory information field Hugepagesize_bytes",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Hugepagesize_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "RDS OS Metrics - Swap Total",
     "type": "timeseries",
     "description": "The total amount of swap memory available, in kilobytes",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_swap_total{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "RDS OS Metrics - Swap Free",
     "type": "timeseries",
     "description": "The total amount of swap memory free, in kilobytes",
     "gridPos": { "h": 5, "w": 5, "x": 5, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_swap_free{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "RDS OS Metrics - Swap Cached",
     "type": "timeseries",
     "description": "The amount of swap memory, in kilobytes, used as cache memory",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_swap_cached{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "RDS OS Metrics - Swap In",
     "type": "timeseries",
     "description": "The total amount of memory, in kilobytes, swapped in from disk",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_swap_in{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "RDS OS Metrics - Swap Out",
     "type": "timeseries",
     "description": "The total amount of memory, in kilobytes, swapped out to disk",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_swap_out{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    }
   ]
  },
  {
   "title": "FILE SYSTEM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Filesystem Files",
     "type": "bargauge",
     "description": "Filesystem total file nodes",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "node_filesystem_files{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Mount Point: {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Node Filesystem Size Bytes",
     "type": "bargauge",
     "description": "Filesystem size in bytes",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Mount Point: {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Node Filesystem Available Bytes",
     "type": "bargauge",
     "description": "Filesystem space available to non-root users in bytes",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Mount Point: {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Node Filesystem Files Free",
     "type": "bargauge",
     "description": "Filesystem total free file nodes",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "node_filesystem_files_free{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Mount Point: {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Node Filesystem Free Bytes",
     "type": "bargauge",
     "description": "Filesystem free space in bytes",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "node_filesystem_free_bytes{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Mount Point: {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Filesystem Total",
     "type": "bargauge",
     "description": "RDS OS Metrics - The total number of disk space available for the file system, in kilobytes",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "rdsosmetrics_fileSys_total{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Mount Point: {{mount_point}}"
      }
     ]
    },
    {
     "title": "Filesystem - Max Files",
     "type": "timeseries",
     "description": "RDS OS Metrics - The maximum number of files that can be created for the file system",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rdsosmetrics_fileSys_maxFiles{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Mount Point: {{mount_point}}"
      }
     ]
    },
    {
     "title": "Filesystem - Used",
     "type": "timeseries",
     "description": "RDS OS Metrics - The amount of disk space used by files in the file system, in kilobytes",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_fileSys_used{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Mount Point: {{mount_point}}"
      }
     ]
    },
    {
     "title": "Filesystem - Used File Percent",
     "type": "timeseries",
     "description": "RDS OS Metrics - The percentage of available files in use",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rdsosmetrics_fileSys_usedFilePercent{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Mount Point: {{mount_point}}"
      }
     ]
    },
    {
     "title": "Filesystem - Used Files",
     "type": "timeseries",
     "description": "RDS OS Metrics - The number of files in the file system",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rdsosmetrics_fileSys_usedFiles{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Mount Point: {{mount_point}}"
      }
     ]
    },
    {
     "title": "Filesystem - Used Percent",
     "type": "timeseries",
     "description": "RDS OS Metrics - The percentage of the file-system disk space in use",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rdsosmetrics_fileSys_usedPercent{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Mount Point: {{mount_point}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DISK IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Disk Read Bytes Total",
     "type": "timeseries",
     "description": "The total number of bytes read successfully",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(node_disk_read_bytes_total{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "Device: {{device}}"
      }
     ]
    },
    {
     "title": "Node Disk Written Bytes Total",
     "type": "timeseries",
     "description": "The total number of bytes written successfully",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rate(node_disk_written_bytes_total{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}[$__rate_interval])",
       "legendFormat": "Device: {{device}}"
      }
     ]
    },
    {
     "title": "Disk IO - avgQueueLen",
     "type": "timeseries",
     "description": "RDS OS Metrics - The number of requests waiting in the I/O device's queue",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "targets": [
      {
       "expr": "rdsosmetrics_diskIO_avgQueueLen{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Device: {{device}}"
      }
     ]
    },
    {
     "title": "Disk IO - Transactions Per Second",
     "type": "timeseries",
     "description": "RDS OS Metrics - The number of I/O transactions per second",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rdsosmetrics_diskIO_tps{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Device: {{device}}"
      }
     ]
    },
    {
     "title": "Disk IO - Read Per Second",
     "type": "timeseries",
     "description": "RDS OS Metrics - The number of read operations per second",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rdsosmetrics_diskIO_await{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Device: {{device}}"
      }
     ]
    },
    {
     "title": "Disk IO - Write Per Second",
     "type": "timeseries",
     "description": "RDS OS Metrics - The number of write operations per second",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rdsosmetrics_diskIO_writeIOsPS{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Device: {{device}}"
      }
     ]
    },
    {
     "title": "Disk IO - Await",
     "type": "timeseries",
     "description": "RDS OS Metrics - The number of milliseconds required to respond to requests, including queue time and service time",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rdsosmetrics_diskIO_await{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Device: {{device}}"
      }
     ]
    },
    {
     "title": "Disk IO - Read Kb Per Second",
     "type": "timeseries",
     "description": "RDS OS Metrics - The number of kilobytes read per second",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "rdsosmetrics_diskIO_readKbPS{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Device: {{device}}"
      }
     ]
    },
    {
     "title": "Disk IO - Read Kb",
     "type": "timeseries",
     "description": "RDS OS Metrics - The total number of kilobytes read",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_diskIO_readKb{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Device: {{device}}"
      }
     ]
    },
    {
     "title": "Disk IO - Write Kb Per Second",
     "type": "timeseries",
     "description": "RDS OS Metrics - The number of kilobytes written per second",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "expr": "rdsosmetrics_diskIO_writeKbPS{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Device: {{device}}"
      }
     ]
    },
    {
     "title": "Disk IO - Write Kb",
     "type": "timeseries",
     "description": "RDS OS Metrics - The total number of kilobytes written",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_diskIO_writeKb{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Device: {{device}}"
      }
     ]
    },
    {
     "title": "Disk IO - Average Request Size",
     "type": "timeseries",
     "description": "RDS OS Metrics - The average request size, in kilobytes",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_diskIO_avgReqSz{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Device: {{device}}"
      }
     ]
    },
    {
     "title": "Disk IO - Percent of CPU",
     "type": "timeseries",
     "description": "RDS OS Metrics - The percentage of CPU time during which requests were issued",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rdsosmetrics_diskIO_util{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Device: {{device}}"
      }
     ]
    },
    {
     "title": "Disk IO - RRQM Per Second",
     "type": "timeseries",
     "description": "RDS OS Metrics - The number of merged read requests queued per second",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rdsosmetrics_diskIO_rrqmPS{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Device: {{device}}"
      }
     ]
    },
    {
     "title": "Disk IO - WRQM Per Second",
     "type": "timeseries",
     "description": "RDS OS Metrics - The number of merged write requests queued per second",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rdsosmetrics_diskIO_wrqmPS{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Device: {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NETWORK",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "RDS OS Metrics - Network Bytes Received",
     "type": "timeseries",
     "description": "The number of bytes received per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rdsosmetrics_network_rx{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "RDS OS Metrics - Network Bytes Uploaded",
     "type": "timeseries",
     "description": "The number of bytes uploaded per second",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "rdsosmetrics_network_tx{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    }
   ]
  },
  {
   "title": "PROCESS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number Processes Per 1 Minute",
     "type": "timeseries",
     "description": "The number of processes requesting CPU time over the last minute",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_load1{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Number Processes Blocked",
     "type": "timeseries",
     "description": "Number of processes blocked waiting for I/O to complete",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_procs_blocked{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Number Processes Running",
     "type": "timeseries",
     "description": "Number of processes in runnable state",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_procs_running{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "RDS OS Metrics - Processes List - CPU Used Percent",
     "type": "timeseries",
     "description": "The percentage of CPU used by the process",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rdsosmetrics_processList_cpuUsedPc{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "ID: {{id}} - {{name}}"
      }
     ]
    },
    {
     "title": "RDS OS Metrics - Processes List - Memory Used Percent",
     "type": "timeseries",
     "description": "The amount of memory used by the process, in kilobytes",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_processList_memoryUsedPc{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "ID: {{id}} - {{name}}"
      }
     ]
    },
    {
     "title": "RDS OS Metrics - Processes List - RSS",
     "type": "timeseries",
     "description": "The amount of RAM allocated to the process, in kilobytes",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_processList_rss{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "ID: {{id}} - {{name}}"
      }
     ]
    },
    {
     "title": "RDS OS Metrics - Process List - VSS",
     "type": "timeseries",
     "description": "The amount of virtual memory allocated to the process, in kilobytes",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "rdsosmetrics_processList_vss{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "ID: {{id}} - {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TASKS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "RDS OS Metrics - Tasks Total",
     "type": "timeseries",
     "description": "The total number of tasks",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rdsosmetrics_tasks_total{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "RDS OS Metrics - Tasks Running",
     "type": "timeseries",
     "description": "The number of tasks that are running",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rdsosmetrics_tasks_running{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "RDS OS Metrics - Task Sleeping",
     "type": "timeseries",
     "description": "The number of tasks that are sleeping",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rdsosmetrics_tasks_sleeping{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "RDS OS Metrics - Task Stopped",
     "type": "timeseries",
     "description": "The number of tasks that are stopped",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rdsosmetrics_tasks_stopped{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "RDS OS Metrics - Tasks Blocked",
     "type": "timeseries",
     "description": "The number of tasks that are blocked",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rdsosmetrics_tasks_blocked{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "RDS OS Metrics - Tasks Zombie",
     "type": "timeseries",
     "description": "The number of child tasks that are inactive with an active parent task",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rdsosmetrics_tasks_zombie{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    }
   ]
  },
  {
   "title": "/PROC/VMSTAT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node vmstat pswpin",
     "type": "timeseries",
     "description": "/proc/vmstat information field pswpin. Number of pages the system has swapped in from disk per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_vmstat_pswpin{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    },
    {
     "title": "Node vmstat pswpout",
     "type": "timeseries",
     "description": "/proc/vmstat information field pswpout. Number of pages the system has swapped out to disk per second",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_vmstat_pswpout{job=\"prom-rds-exporter\",region=~\"$Region\",exported_instance=~\"$Instance\"}",
       "legendFormat": "Value"
      }
     ]
    }
   ]
  }
 ]
}